apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "headscale.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headscale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: headscale
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.headscale.image.repository }}:{{ .Values.headscale.image.tag | default .Chart.AppVersion }}"
          command:
            {{- toYaml .Values.headscale.image.command | nindent 12 }}
          imagePullPolicy: {{ .Values.headscale.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80 
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.headscale.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.headscale.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.headscale.resources | nindent 12 }}
          {{- with .Values.headscale.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.headplane.enabled }}
        - name: headplane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.headplane.image.repository }}:{{ .Values.headplane.image.tag | default latest }}"
          imagePullPolicy: {{ .Values.headplane.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.headplane.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.headplane.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.headplane.resources | nindent 12 }}
          {{- with .Values.headplane.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: DEBUG
              value: {{ .Values.config.headplane.debug | default "false" }}
            - name: HEADSCALE_INTEGRATION
              value: 'kubernetes'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.secret.name | default include "headplane.fullname" . }} 
                  key: cookie
            - name: COOKIE_SECURE
              value: false
            - name: ROOT_API_KEY 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.secret.name | default include "headplane.fullname" . }} 
                  key: 
            - name: DISABLE_API_KEY_LOGIN 
              value: {{ .Values.config.headplane.api.disableLogin | default "true" }}

        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
