{{- if .Values.headplane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headplane.fullname" . }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.headplane.service.type }}
  ports:
    - port: {{ .Values.headplane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "headplane.selectorLabels" . | nindent 4 }}
{{- end }}