{{- if .Values.headplane.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headplane.fullname" . }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "headplane.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "headscale.serviceAccountName" . }}
{{- end }}