apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.headscale.service.type }}
  ports:
    - port: {{ .Values.headscale.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
