{{- if .Values.config.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headplane.fullname" . }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
type: Opaque
data:
  cookie: {{ .Values.config.cookie.value | toString | b64enc | quote }}
  apiKey: {{ .Values.config.headplane.api.key | toString | b64enc | quote }}
{{- end -}}

