{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
data:
  cookie: {{ .Values.headplane.cookie.value | toString | b64enc | quote }}
  apiKey: {{ .Values.headplane.api.key | toString | b64enc | quote }}
{{- end -}}

